def Count(c: str) -> str:
    Count_A = len([i for i in c if i == 'A'])
    Count_C = len([i for i in c if i == 'C'])
    Count_G = len([i for i in c if i == 'G'])
    Count_T = len([i for i in c if i == 'T'])

    result:str = f"{Count_A} {Count_C} {Count_G} {Count_T}"
    print(result)


if __name__ == '__main__':
    Count("GCGTCATGGGATGCTATGTCGAGGGAACAGAGTTAATCGCCTTAACGTGAGTCCAGTTGAGTCAGAGGCGACTTGGGGCGGACCGGTCTTTTAGGTGCCTTATGACCGGTGCAGGACTATTTGATGTCGACGGGCGCCTGCGGTTTTAAGCCACCTGTGTCCTTCTCAGTCCGGGAGGCGAATAATGCGGCGGCCGCCTCATGTTACATGCTTCAGATCAAGCCGAAGTGTGCATGAGTCCTACCTTCAATTCCCAATGGACTACTAGGGCTATCGGGTGATCTTTCCACTGCTGTAATGTCGAGTCGTTGGGCTAAATCCCGCTGTAACGGGTTTATATCACCTATGAGAAAGCCACGGAGGCCGAACGCAGTTGAGAGCGGGACCATGTCAGAAACGATAGTATGAATAACTGGACCTCACGCAGATACTTCCTGCCCGAACTCCGATATTGCTGCCTATACTCACATAGAGTTCGCTATTAGAATCCATCAGTAGATAAGTGGCGGGTACATGATGGTTCCAGATATATTAAATAGTGTTTCTCCTCGGAGAAATTTCATCACTACTACACGTTAAAAGATGCTCGTCAGTAGTAGGCAGGACTGCAGAATGACCGCGGCGCTTCCCCATATGTGGCACGATCCAAGGCAGCTGCACAAACTAGGGGCAGGCGGGCCTCGATGAGGTCAGGGATAGTTCATCATGGCAATTAGCATGGGTCGCGATTTCCCCCATCGTCGTATTCACCTAGATTGGCTGATATTGATATTACCTAGACCCATACTGTCTGAGGGGGCGCGAGCTAAAACTAGCCCCCGTCCCGTTGCGGAGCCGTACTAATCAACCAATAGATTATAAGCCG")

